services:
  mysql:
    image: mysql:8.3
    container_name: mysql_northwind
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: northwind
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: northback_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/northwind?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql_data: